name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    defaults:
      run:
        working-directory: test

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: build x86
      shell: cmd
      run: ..\build.bat . x86
      working-directory: test

    - name: build x64
      shell: cmd
      run: ..\build.bat . x64
      working-directory: test

    - name: test x64
      shell: cmd
      run: sc create LdkTest binpath= "${{ github.workspace }}\build_x64\Debug\LdkTest.sys" displayname= "Ldk Test" start= demand type= kernel
      working-directory: test
      
    - name: test x64
      shell: cmd
      run: sc query LdkTest
      working-directory: test
  
    - name: test x64
      shell: cmd
      run: sc start LdkTest
      working-directory: test
      
    - name: test x64
      shell: cmd
      run: sc stop LdkTest
      working-directory: test
